config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'search#index'
  resources :search
  put '/search' => 'search#update', as: :search_update
  resources :adminsettings , only:[:edit,:update]

  # Api controller
  get '/api/search/:term(/page_size/:page_size)(/page_num/:page_num)(/exact_search/:exact_search)(/order_by/:order_by)'\
      '(/order_by_direction/:order_by_direction)', to: 'api#search', :constraints => {:term => /[^\/]+/}
  get '/api/threat/:id', to: 'api#threat', :constraints => {:id => /[^\/]+/}
  get '/api/analytics/', to: 'api#analytics'
  get '/api/search_api/', to: 'search#search_api'
  post '/api/search_api/', to: 'search#search_api'
  get '/analytics', to: 'api#analytics'
  get '/reverse-admin-flag', to: 'adminsettings#reverse_admin_flag'
end

app/models/search.rb
# require 'elasticsearch-persistence'
# Documentation # TODO:Documentation
class Search < ApplicationRecord
  include Elasticsearch::Persistence::Model
  include Elasticsearch::DSL
  # include ActiveRecord::Base
  # include Elasticsearch::Model::Callbacks

  class << self
    def index=(name)
      index_name name
    end

    def indices
      Elasticsearch::Model.client.cat.indices(h: 'index', format: 'json', index: 'threatdb*', s: 'index')
                          .map {|x| x['index']}.sort.reverse!
    end
  end

  index_name indices.first
  document_type 'threatdb_tri'

  attribute :id, String, mapping: { fields: { '@id'.to_sym => { type: 'string' } } }
  attribute :_index, String, mapping: { fields: { index: { type: 'string' } } }
  attribute :threat_id, String, mapping: { fields: { threat_id: { type: 'string' } } }
  attribute :host, String, mapping: { fields: { host: { type: 'string' } } }
  attribute :confidence, Float, mapping: { fields: { confidence: { type: 'float' } } }
  attribute :threat_tri, Float, mapping: { fields: { threat_tri: { type: 'double' } } }
  attribute :risk, Float, mapping: { fields: { risk: { type: 'float' } } }
  attribute :type, String, mapping: { fields: { type: { type: 'string' } } }
  attribute :type_description, String, mapping: { fields: { type_description: { type: 'string' } } }
  attribute :category, String, mapping: { fields: { category: { type: 'string' } } }
  attribute :category_description, String, mapping: { fields: { category_description: { type: 'string' } } }
  attribute :threat_type, String, mapping: { fields: { threat_type: { type: 'string' } } }
  attribute :country, String, mapping: { fields: { country: { type: 'string' } } }
  attribute :country_code, String, mapping: { fields: { country_code: { type: 'string' } } }
  attribute :continent_code, String, mapping: { fields: { continent_code: { type: 'string' } } }
  attribute :city, String, mapping: { fields: { city: { type: 'string' } } }
  # location = [long, lat]
  attribute :location, Array, mapping: { fields: { location: { type: 'double' } } }
  attribute :asn, String, mapping: { fields: { asn: { type: 'string' } } }
  attribute :asn_registry, String, mapping: { fields: { asn_registry: { type: 'string' } } }
  attribute :logid, String, mapping: { fields: { logid: { type: 'string' } } }
  attribute :source_ids, Array, mapping: { fields: { source_ids: { type: 'string' } } }

  attribute :global_filter_time, Bignum, mapping: { fields: { '&global_filter_time'.to_sym => { type: 'long' } } }
  attribute :logstash_backend, String, mapping: { fields: { 'logstash_backend'.to_sym => { type: 'string' } } }
  attribute :logstash_febe_latency_sec, String, mapping: { fields: { '&logstash_febe_latency_sec'.to_sym => { type: 'string' } } }
  attribute :logstash_frontend, String, mapping: { fields: { '&logstash_frontend'.to_sym => { type: 'string' } } }
  attribute :raw_message_bytesize, Integer, mapping: { fields: { '&raw_message_bytesize'.to_sym => { type: 'integer' } } }
  attribute :vendor_filter_time, Bignum, mapping: { fields: { '&vendor_filter_time'.to_sym => { type: 'long' } } }
  alias_attribute :'&global_filter_time', :global_filter_time
  alias_attribute :'&logstash_backend', :logstash_backend
  alias_attribute :'&logstash_febe_latency_sec', :logstash_febe_latency_sec
  alias_attribute :'&logstash_frontend', :logstash_frontend
  alias_attribute :'&raw_message_bytesize', :raw_message_bytesize
  alias_attribute :'&vendor_filter_time', :vendor_filter_time

  attribute :id, String, mapping: { fields: { '@id'.to_sym => { type: 'string' } } }
  attribute :srcevent, String, mapping: { fields: { '@srcevent'.to_sym => { type: 'string' } } }
  attribute :timestamp, DateTime, mapping: { fields: { '@timestamp'.to_sym => { type: 'datetime', format: 'dateOptionalTime' } } }
  attribute :vendor, String, mapping: { fields: { '@vendor'.to_sym => { type: 'string' } } }
  attribute :version, Integer, mapping: { fields: { '@version'.to_sym => { type: 'integer' } } }
  alias_attribute :'@id', :id
  alias_attribute :'@srcevent', :srcevent
  alias_attribute :'@timestamp', :timestamp
  alias_attribute :'@vendor', :vendor
  alias_attribute :'@version', :version
end

app/controllers/search_controller.rb
require 'elasticsearch/model'
require 'elasticsearch/persistence/model'
require 'elasticsearch/dsl'

# Documentation # TODO: Documentation
class SearchController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :update, :destroy]

  def index
    if Adminsetting.count.zero?
      new_adminsetting = Adminsetting.new
      new_adminsetting.save
    end
    @skip_columns = Adminsetting.first.preferences
    @search_result = Search.search(query: {match_all: {}}, size: 1)
  end

  def show
    response = Search.search(query: {match: {_id: params[:id]}})
    if response.total != 1
      flash[:warning] = 'Threat was not found'
      redirect_to root_path
    else
      @skip_columns = Adminsetting.first.preferences
      @search_result = response.first
      threat_id = @search_result.threat_id

      @tri_rounded = (@search_result.threat_tri*100).round(1)
      @fa_class = case @tri_rounded
                   when 0..33
                     'fa-check'
                   when 34..66
                     'fa-warning'
                   else
                    'fa-times'
                 end

      @histogram_data = []
      Search.indices.each do |index|
        Search.index = index
        response = Search.search(query: {match: {threat_id: threat_id}}).first
        date = Date.strptime(index[9, 10], '%Y.%m.%d')
        if response
          @histogram_data << {date: date.strftime('%F'), tri: response.threat_tri}
        else
          @histogram_data << {date: date.strftime('%F'), tri: 0}
        end
      end
      @histogram_data = @histogram_data.reverse.to_json
      Search.index = Search.indices.first
    end
  end

  def edit
    @skip_columns = Set.new
    @search_result = Search.search(query: {match: {_id: params[:id]}}).first
  end

  def update
    @search_result = Search.search(query: {match: {_id: params[:search][:id]}}).first
    permitted_params = update_params
    @search_result.update_attributes(permitted_params.to_h)
    sleep 3
    flash[:success] = 'Record successfully updated!'
    redirect_to edit_search_url(@search_result)
  end

  def destroy
    begin
      @search_result = Search.search(query: {match: {_id: params[:id]}}).first
      @search_result.destroy
      flash[:success] = 'Record successfully deleted!' if @search_result.destroyed?
    rescue
      flash[:warning] = 'Record could not be deleted!'
    end
    true
  end

  def search_api
    term = '', page_size = 10, page_num = 0, exact_search = true, order_by = '_score', direction = 'desc', regex = false
    term = params[:term] if params.key?(:term)
    regex = params[:regex] if params.key?(:regex)
    page_size = params[:length].to_i if params.key?(:length)
    page_num = params[:start].to_i if params.key?(:start)
    order_by = params[:order_column_name] if params.key?(:order_column_name)
    direction = 'asc' if params.key?(:order_dir) && params[:order_dir] == 'asc'

    search_result = Search.search query: {bool: {should: [{term: {threat_id: term}}, {term: {country: term}}]}},
                                  size: page_size, from: page_num, sort: [{order_by.to_sym => direction}]
    render json: {draw: params[:draw], recordsTotal: search_result.total, recordsFiltered: search_result.total, data: search_result}
  end

  private

  def update_params
    params.require(:search).permit(:confidence, :risk, :type_description, :category_description, :country,
                                   :continent_code, :asn_registry, :host, :threat_tri, :type,
                                   :category, :threat_type, :country_code, :city, :asn, :source_ids => [], :location => [])
  end
end

app/views/search/edit.html.erb
<% content_for :head_stylesheets do %>
    <%= stylesheet_link_tag 'application-threat-edit' %>
<% end %>
<% content_for :head_javascripts do %>

<% end %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Edit threat</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> alert-dismissible" role="alert" style="padding-left:0!important;"><%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
      </div>
  <% end %>
</div>
<!-- /.row -->

<div class="row">
  <%= form_tag search_update_path, {method: 'put', class: 'form-horizontal'} do %>
      <%#= form_for @search_result, url: search_update_path, html: {method: 'put', class: 'form-horizontal'} do |f| %>
      <div class="col-lg-6">
        <% i = 0 %>
        <% @search_result.attributes.each do |name, value| %>
            <% i += 1 %>
            <% next if i%2 == 0 %>
            <% next if @skip_columns.include?(name.to_s) %>
            <div class="form-group">
              <%= label_tag "search[#{name}]", t(name), class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <% if value.class == Array %>
                    <% value.each do |array_value| %>
                        <%= text_field_tag "search[#{name}][]", array_value, class: 'form-control' %>
                    <% end %>
                <% else %>
                    <%= text_field_tag "search[#{name}]", value, class: 'form-control' %>
                <% end %>
              </div>
            </div>
            <!-- /.form-group -->
        <% end %>
        <div class="form-group">
          <div class="col-md-offset-4 col-md-8">
            <%= submit_tag 'Submit', class: 'btn btn-primary' %>
          </div>
        </div>
        <!-- /.form-group -->
      </div>
      <!-- /.col-lg-6 -->
      <div class="col-lg-6">
        <% i = 0 %>
        <% @search_result.attributes.each do |name, value| %>
            <% i +=1 %>
            <% next if i%2 == 1 %>
            <% next if @skip_columns.include?(name.to_s) %>
            <div class="form-group">
              <%= label_tag "search[#{name}]", t(name), class: 'col-md-4 control-label' %>
              <div class="col-md-6">
                <% if value.class == Array %>
                    <% value.each do |array_value| %>
                        <%= text_field_tag "search[#{name}][]", array_value, class: 'form-control' %>
                    <% end %>
                <% else %>
                    <%= text_field_tag "search[#{name}]", value, class: 'form-control' %>
                <% end %>
              </div>
            </div>
            <!-- /.form-group -->
        <% end %>
      </div>
      <!-- /.col-lg-6 -->
  <% end %>
  <!-- /form -->
</div>
<!-- /.row -->

<% content_for :body_javascripts do %>

<% end %>

app/views/search/index.html.erb
<% content_for :head_stylesheets do %>
    <%= stylesheet_link_tag 'application-index' %>
<% end %>
<% content_for :head_javascripts do %>

<% end %>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-lg-12">
      <h1 class="page-header">Threat records</h1>
    </div>
  </div>
  <!-- /.row -->

  <div class="row-fluid">
    <div class="col-lg-12">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %> alert-dismissible" role="alert"><%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
          </div>
      <% end %>
    </div>
  </div>
  <!-- /.row -->

  <% if @search_result && @search_result.length > 0 %>
      <div class="row-fluid">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                <tr>
                  <% @search_result.first.attributes.each do |name, value| %>
                      <% next if name == :created_at || name == :updated_at %>
                      <% next if current_user && !current_user.is_admin && @skip_columns.include?(name.to_s) %>
                      <th class="<%= name %>" data-name="<%= name %>" data-data="<%= name %>" data-orderable="<%= name != :threat_id %>"><%= t(name) %></th>
                  <% end %>
                  <% if current_user && current_user.is_admin %>
                      <th class="edit-button" data-data="edit-button" data-name="edit-button" data-searchable="false" data-orderable="false"></th>
                      <th class="delete-button" data-data="delete-button" data-name="delete-button" data-searchable="false" data-orderable="false"></th>
                  <% end %>
                </tr>
                </thead>
              </table>
              <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
      </div>
  <% end %>

  <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="confirm-delete" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          Delete threat
        </div>
        <div class="modal-body" id="modal-body">
          Are you sure you want to delete?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <a class="btn btn-danger btn-ok">Delete</a>
        </div>
      </div>
    </div>
  </div>

  <% content_for :body_javascripts do %>
      <%= javascript_include_tag 'application-search-index' %>
      <%= javascript_include_tag 'application-search-index-admin' if current_user && current_user.is_admin %>
  <% end %>

app/views/search/show.html.erb
<% content_for :head_stylesheets do %>

<% end %>
<% content_for :head_javascripts do %>

<% end %>
<%
  panel_color = case @tri_rounded
                  when 0..33
                    'green'
                  when 34..66
                    'yellow'
                  else
                    'red'
                end
%>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Threat: <%= @search_result.threat_id %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> alert-dismissible" role="alert" style="padding-left:0!important;"><%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
      </div>
  <% end %>
</div>
<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-table fa-fw"></i> Threat Info
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="list-group">
          <% if @search_result %>
              <% @search_result.attributes.each do |name, value| %>
                  <% next if current_user && !current_user.is_admin && @skip_columns.include?(name.to_s) %>
                  <% next if value.nil? || value == '' %>
                  <div class="list-group-item">
                    <%= value %>
                    <span class="pull-right text-muted small"><em><%= t(name) %></em></span>
                  </div>
              <% end %>
          <% end %>
        </div>
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-4 -->
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-bar-chart-o fa-fw"></i> Gauge Bar
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div id="kuma-gauge" class="js-gauge gauge col-xs-6" data-value="<%= @tri_rounded %>"></div>

        <div class="col-xs-6">
          <div class="panel panel-<%= panel_color %>">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa <%= @fa_class %> fa-3x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge"><%= @tri_rounded %>%</div>
                  <div>TRI</div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-bar-chart-o fa-fw"></i> Histogram
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <script>var histogram_data = <%= @histogram_data.html_safe %>;</script>
        <div id="histogram-chart"></div>
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-8 -->
</div>
<!-- /.row -->

<% content_for :body_javascripts do %>
    <%= javascript_include_tag 'application-threat-show' %>
<% end %>